---
abstract: 'MessagePack serialising/deserialising'
author:
  - 'Tokuhiro Matsuno'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-MessagePack
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Test::More: 0.94
  XSLoader: 0.1
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/msgpack/msgpack
version: 0.27
